apiVersion: v1
kind: Service
metadata:
  name: book-service
spec:
  type: NodePort  # or LoadBalancer for external access in production
  selector:
    app: book-service
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001  # Optional: You can specify a custom NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-service
  template:
    metadata:
      labels:
        app: book-service
    spec:
      containers:
        - name: book-service
          image: book-service:latest
          imagePullPolicy: IfNotPresent  # This is more common for production environments
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/bookdb
            - name: SPRING_DATASOURCE_USERNAME
              value: bookuser  # If this is your username
            - name: SPRING_DATASOURCE_PASSWORD
              value: bookpass  # If this is your password
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
