services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: library_books
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - library-network

  book-service:
    build: .
    container_name: book-service
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/library_books
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - "8080:8080"
    networks:
      - library-network

networks:
  library-network:
    driver: bridge
